import { BOOK_DESCRIPTIONS } from "./descriptions";

export type BuyLink = {
  store: "amazon" | "google-play";
  url: string;
};

export interface Book {
  id: string;
  title: string;
  author: string;
  price: number;
  category: string;
  series: string;
  coverImage: string;
  isFeatured?: boolean;
  buyLinks: BuyLink[];
  description?: string;
}

export const CATEGORIES = [
  "All",
  "Engineering",
  "Programming & Technology",
  "Medical Science",
  "Science",
  "Business & Management",
  "Self-Help & Skills",
  "Children's",
  "Educational Books",
];

const gp = (id: string): BuyLink => ({
  store: "google-play",
  url: `https://play.google.com/store/books/details?id=${id}`,
});

const amz = (asin: string): BuyLink => ({
  store: "amazon",
  url: `https://www.amazon.com/dp/${asin}`,
});

const RAW: Omit<Book, "description">[] = [
  // ── Original KF / Itorzo Publications ──────────────────────────────────────
  {
    id: "1620",
    title: "The Anatoly Method: 8 Weeks to Strength & Aesthetics",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Self-Help & Skills",
    series: "Fitness & Strength",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/41ZvHq4f0+L._SY445_SX342_QL70_FMwebp_.jpg",
    buyLinks: [amz("B0FSC3J5DH")],
  },
  {
    id: "1591",
    title: "Animals in the Forest",
    author: "Leslie Pearl N. Castillo, LPT",
    price: 7.99,
    category: "Children's",
    series: "Kids",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/51h5YNkhoHL._SX342_SY445_QL70_FMwebp_.jpg",
    buyLinks: [amz("B0FXZBGXZH")],
  },
  {
    id: "1589",
    title: "The Alphabets",
    author: "Leslie Pearl N. Castillo, LPT",
    price: 7.99,
    category: "Children's",
    series: "Kids",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/411qMDm6beL._SX342_SY445_QL70_ML2_.jpg",
    buyLinks: [amz("B0FWWD62FP")],
  },
  {
    id: "1587",
    title: "Tracing Numbers",
    author: "Leslie Pearl N. Castillo, LPT",
    price: 7.99,
    category: "Children's",
    series: "Kids",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/41V-Lt77n-L._SX342_SY445_QL70_FMwebp_.jpg",
    buyLinks: [amz("B0FWZB9LT1")],
  },
  {
    id: "1584",
    title: "How To Make Trending AI Videos for Instagram, Youtube, Tiktok",
    author: "Leslie Pearl N. Castillo, LPT",
    price: 11.99,
    category: "Self-Help & Skills",
    series: "AI Skill",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/51V+qtPcIAL._SY445_SX342_QL70_FMwebp_.jpg",
    isFeatured: true,
    buyLinks: [amz("B0FWZ7YCRW")],
  },
  {
    id: "1582",
    title: "Enhancing Communication Skills",
    author: "Leslie Pearl N. Castillo, LPT",
    price: 11.99,
    category: "Self-Help & Skills",
    series: "Communication Skill",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/31wmD1vPJpL._SY445_SX342_QL70_FMwebp_.jpg",
    isFeatured: true,
    buyLinks: [amz("B0FWZ5TY4S")],
  },
  {
    id: "1580",
    title: "Basic Computer Application Course",
    author: "Leslie Pearl N. Castillo, LPT",
    price: 12.99,
    category: "Programming & Technology",
    series: "Programming & Computer Science",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/414pQJt-WXL._SY445_SX342_QL70_FMwebp_.jpg",
    buyLinks: [amz("B0FX1LSM8J")],
  },
  {
    id: "1578",
    title: "15 Best AI Prompts For Generating Trending AI Videos",
    author: "Leslie Pearl N. Castillo, LPT",
    price: 9.99,
    category: "Self-Help & Skills",
    series: "AI Skill",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/41v0zyGyhoL._SY445_SX342_QL70_FMwebp_.jpg",
    buyLinks: [amz("B0FX1MX2DZ")],
  },
  {
    id: "1575",
    title: "Preparing for Global Success",
    author: "Leslie Pearl N. Castillo, LPT",
    price: 13.99,
    category: "Self-Help & Skills",
    series: "Life Sciences",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/41pzGum3igL._SX342_SY445_QL70_FMwebp_.jpg",
    buyLinks: [amz("B0FXKH51V5")],
  },

  // ── Medical Science ────────────────────────────────────────────────────────
  {
    id: "1369",
    title: "Internal Medicine",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Medical Science",
    series: "Medical Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/5N1DDwAAQBAJ.jpg",
    isFeatured: true,
    buyLinks: [gp("5N1DDwAAQBAJ")],
  },
  {
    id: "1353",
    title: "Essential Neurosurgery",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Medical Science",
    series: "Medical Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/sCZHBAAAQBAJ.jpg",
    buyLinks: [gp("sCZHBAAAQBAJ")],
  },
  {
    id: "1349",
    title: "Human Body Anatomy",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Medical Science",
    series: "Medical Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/uCVOBAAAQBAJ.jpg",
    isFeatured: true,
    buyLinks: [gp("uCVOBAAAQBAJ")],
  },
  {
    id: "1325",
    title: "Basics of Pathology",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Medical Science",
    series: "Medical Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/XhvfCQAAQBAJ.jpg",
    buyLinks: [gp("XhvfCQAAQBAJ")],
  },
  {
    id: "1317",
    title: "Basics of Biology",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Medical Science",
    series: "Medical Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/TESDBgAAQBAJ.jpg",
    buyLinks: [gp("TESDBgAAQBAJ")],
  },
  {
    id: "1293",
    title: "Pharmacology",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Medical Science",
    series: "Medical Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/zVpNBAAAQBAJ.jpg",
    buyLinks: [gp("zVpNBAAAQBAJ")],
  },
  {
    id: "1283",
    title: "Fundamentals of Biochemistry",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Medical Science",
    series: "Medical Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/2u5vCQAAQBAJ.jpg",
    buyLinks: [gp("2u5vCQAAQBAJ")],
  },
  {
    id: "1281",
    title: "Top Common Diseases",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Medical Science",
    series: "Medical Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/hNNeCgAAQBAJ.jpg",
    buyLinks: [gp("hNNeCgAAQBAJ")],
  },
  {
    id: "1263",
    title: "Obstetrics and Gynaecology",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Medical Science",
    series: "Medical Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/stzxCQAAQBAJ.jpg",
    buyLinks: [gp("stzxCQAAQBAJ")],
  },
  {
    id: "1257",
    title: "Toxicology",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Medical Science",
    series: "Medical Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/Sf5oBQAAQBAJ.jpg",
    buyLinks: [gp("Sf5oBQAAQBAJ")],
  },
  {
    id: "1251",
    title: "Men and Women Health Book",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Medical Science",
    series: "Medical Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/J09VCgAAQBAJ.jpg",
    buyLinks: [gp("J09VCgAAQBAJ")],
  },
  {
    id: "1241",
    title: "Medicinal Chemistry",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Medical Science",
    series: "Medical Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/8eweBQAAQBAJ.jpg",
    buyLinks: [gp("8eweBQAAQBAJ")],
  },
  {
    id: "1239",
    title: "Introduction to Organic Synthesis",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Medical Science",
    series: "Medical Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/P-uSBwAAQBAJ.jpg",
    buyLinks: [gp("P-uSBwAAQBAJ")],
  },

  // ── Engineering ────────────────────────────────────────────────────────────
  {
    id: "1367",
    title: "Automobile Engineering",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/xB9XBAAAQBAJ.jpg",
    buyLinks: [gp("xB9XBAAAQBAJ")],
  },
  {
    id: "1365",
    title: "Engineering Materials",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/kD8fCgAAQBAJ.jpg",
    buyLinks: [gp("kD8fCgAAQBAJ")],
  },
  {
    id: "1363",
    title: "Mechanical Engineering",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/ZM59BgAAQBAJ.jpg",
    buyLinks: [gp("ZM59BgAAQBAJ")],
  },
  {
    id: "1361",
    title: "Engineering Thermodynamics",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/i9QhCQAAQBAJ.jpg",
    buyLinks: [gp("i9QhCQAAQBAJ")],
  },
  {
    id: "1351",
    title: "Machine Design Engineering",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/jiiFBAAAQBAJ.jpg",
    buyLinks: [gp("jiiFBAAAQBAJ")],
  },
  {
    id: "1345",
    title: "Optical Engineering",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/_0ZGDgAAQBAJ.jpg",
    buyLinks: [gp("_0ZGDgAAQBAJ")],
  },
  {
    id: "1341",
    title: "Vibration & Noise Engineering",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/VzJZBAAAQBAJ.jpg",
    buyLinks: [gp("VzJZBAAAQBAJ")],
  },
  {
    id: "1339",
    title: "Electrical Engineering",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/M7mNBQAAQBAJ.jpg",
    buyLinks: [gp("M7mNBQAAQBAJ")],
  },
  {
    id: "1337",
    title: "Aerospace Engineering",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/5mpUCwAAQBAJ.jpg",
    buyLinks: [gp("5mpUCwAAQBAJ")],
  },
  {
    id: "1335",
    title: "Handbook of Mechanical and Materials Engineering",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/3PwEEAAAQBAJ.jpg",
    buyLinks: [gp("3PwEEAAAQBAJ")],
  },
  {
    id: "1331",
    title: "Nanotechnology and Nanoscience",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/Ie3ODAAAQBAJ.jpg",
    buyLinks: [gp("Ie3ODAAAQBAJ")],
  },
  {
    id: "1327",
    title: "Digital Electronics",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/V7bnDAAAQBAJ.jpg",
    buyLinks: [gp("V7bnDAAAQBAJ")],
  },
  {
    id: "1309",
    title: "Renewable Energy Engineering",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/vhkFCgAAQBAJ.jpg",
    buyLinks: [gp("vhkFCgAAQBAJ")],
  },
  {
    id: "1301",
    title: "Engineering Mechanics",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/oPo4BQAAQBAJ.jpg",
    buyLinks: [gp("oPo4BQAAQBAJ")],
  },
  {
    id: "1297",
    title: "Automation and Robotics",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/8jiMCwAAQBAJ.jpg",
    buyLinks: [gp("8jiMCwAAQBAJ")],
  },
  {
    id: "1289",
    title: "Engineering Physics",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/OcylBwAAQBAJ.jpg",
    buyLinks: [gp("OcylBwAAQBAJ")],
  },
  {
    id: "1287",
    title: "Civil Engineering",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/VUzVBAAAQBAJ.jpg",
    buyLinks: [gp("VUzVBAAAQBAJ")],
  },
  {
    id: "1259",
    title: "Electronics Engineering",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/exlZBAAAQBAJ.jpg",
    buyLinks: [gp("exlZBAAAQBAJ")],
  },
  {
    id: "1255",
    title: "Basics of Fluid Mechanics",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/CJnMBgAAQBAJ.jpg",
    buyLinks: [gp("CJnMBgAAQBAJ")],
  },
  {
    id: "1245",
    title: "Mechanical Instruments and Tools",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/QA6LBgAAQBAJ.jpg",
    buyLinks: [gp("QA6LBgAAQBAJ")],
  },
  {
    id: "1235",
    title: "Electrical and Electronics Engineering",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/j4j_DwAAQBAJ.jpg",
    buyLinks: [gp("j4j_DwAAQBAJ")],
  },
  {
    id: "1233",
    title: "Engineering Chemistry",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Engineering",
    series: "Engineering Core Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/iZJyCQAAQBAJ.jpg",
    buyLinks: [gp("iZJyCQAAQBAJ")],
  },

  // ── Programming & Technology ───────────────────────────────────────────────
  {
    id: "1355",
    title: "Management Information System",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Programming & Technology",
    series: "Programming & Computer Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/UDlYBAAAQBAJ.jpg",
    buyLinks: [gp("UDlYBAAAQBAJ")],
  },
  {
    id: "1347",
    title: "Beginning ASP.NET",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Programming & Technology",
    series: "Programming & Computer Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/WVDBCAAAQBAJ.jpg",
    buyLinks: [gp("WVDBCAAAQBAJ")],
  },
  {
    id: "1333",
    title: "C Programming Language",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Programming & Technology",
    series: "Programming & Computer Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/7PdCBgAAQBAJ.jpg",
    buyLinks: [gp("7PdCBgAAQBAJ")],
  },
  {
    id: "1319",
    title: "C++ Programming Language",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Programming & Technology",
    series: "Programming & Computer Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/ydb0BgAAQBAJ.jpg",
    buyLinks: [gp("ydb0BgAAQBAJ")],
  },
  {
    id: "1315",
    title: "Data Structures and Algorithms",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Programming & Technology",
    series: "Programming & Computer Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/s0PaBgAAQBAJ.jpg",
    buyLinks: [gp("s0PaBgAAQBAJ")],
  },
  {
    id: "1313",
    title: "Learn Computer Science",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Programming & Technology",
    series: "Programming & Computer Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/9qL0CAAAQBAJ.jpg",
    buyLinks: [gp("9qL0CAAAQBAJ")],
  },
  {
    id: "1311",
    title: "Python Programming",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Programming & Technology",
    series: "Programming & Computer Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/WUPuCAAAQBAJ.jpg",
    buyLinks: [gp("WUPuCAAAQBAJ")],
  },
  {
    id: "1307",
    title: "Beginning Linux Programming",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Programming & Technology",
    series: "Programming & Computer Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/I892CAAAQBAJ.jpg",
    buyLinks: [gp("I892CAAAQBAJ")],
  },
  {
    id: "1299",
    title: "Compiler Design",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Programming & Technology",
    series: "Programming & Computer Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/lau9BwAAQBAJ.jpg",
    buyLinks: [gp("lau9BwAAQBAJ")],
  },
  {
    id: "1279",
    title: "Software Testing",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Programming & Technology",
    series: "Programming & Computer Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/R6taBAAAQBAJ.jpg",
    buyLinks: [gp("R6taBAAAQBAJ")],
  },
  {
    id: "1277",
    title: "Java Programming for Beginners",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Programming & Technology",
    series: "Programming & Computer Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/Hn8TBwAAQBAJ.jpg",
    buyLinks: [gp("Hn8TBwAAQBAJ")],
  },
  {
    id: "1275",
    title: "Learning PHP and MySQL",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Programming & Technology",
    series: "Programming & Computer Science Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/bMVTBwAAQBAJ.jpg",
    buyLinks: [gp("bMVTBwAAQBAJ")],
  },

  // ── Science ────────────────────────────────────────────────────────────────
  {
    id: "1359",
    title: "Zoology: An Introduction",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Science",
    series: "Science Foundation Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/gvg9DgAAQBAJ.jpg",
    buyLinks: [gp("gvg9DgAAQBAJ")],
  },
  {
    id: "1357",
    title: "World Geography",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Science",
    series: "Science Foundation Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/1jEmCwAAQBAJ.jpg",
    buyLinks: [gp("1jEmCwAAQBAJ")],
  },
  {
    id: "1323",
    title: "Short Tricks of Math",
    author: "Knowledge Flow",
    price: 7.99,
    category: "Science",
    series: "Science Foundation Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/iqY-DwAAQBAJ.jpg",
    buyLinks: [gp("iqY-DwAAQBAJ")],
  },
  {
    id: "1305",
    title: "Basics of Math",
    author: "Knowledge Flow",
    price: 7.99,
    category: "Science",
    series: "Science Foundation Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/85r1BQAAQBAJ.jpg",
    buyLinks: [gp("85r1BQAAQBAJ")],
  },
  {
    id: "1295",
    title: "Botany: The Life of Plants",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Science",
    series: "Science Foundation Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/vQigDwAAQBAJ.jpg",
    buyLinks: [gp("vQigDwAAQBAJ")],
  },
  {
    id: "1273",
    title: "Astronomy: Science of Universe",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Science",
    series: "Science Foundation Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/8J6cDwAAQBAJ.jpg",
    buyLinks: [gp("8J6cDwAAQBAJ")],
  },
  {
    id: "1267",
    title: "Pandemic Coronavirus: A Basic Guide",
    author: "Knowledge Flow",
    price: 7.99,
    category: "Science",
    series: "Science Foundation Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/j47ZDwAAQBAJ.jpg",
    buyLinks: [gp("j47ZDwAAQBAJ")],
  },
  {
    id: "1249",
    title: "Basics of Physics",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Science",
    series: "Science Foundation Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/IX1hCgAAQBAJ.jpg",
    buyLinks: [gp("IX1hCgAAQBAJ")],
  },
  {
    id: "1231",
    title: "Basics of Chemistry",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Science",
    series: "Science Foundation Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/X7E9CwAAQBAJ.jpg",
    buyLinks: [gp("X7E9CwAAQBAJ")],
  },

  // ── Business & Management ─────────────────────────────────────────────────
  {
    id: "1329",
    title: "Psychology",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Business & Management",
    series: "Management & Business Studies Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/OfhcDwAAQBAJ.jpg",
    buyLinks: [gp("OfhcDwAAQBAJ")],
  },
  {
    id: "1321",
    title: "Financial Management",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Business & Management",
    series: "Management & Business Studies Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/-Z1SBAAAQBAJ.jpg",
    buyLinks: [gp("-Z1SBAAAQBAJ")],
  },
  {
    id: "1303",
    title: "Basic Economics",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Business & Management",
    series: "Management & Business Studies Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/30HIBgAAQBAJ.jpg",
    buyLinks: [gp("30HIBgAAQBAJ")],
  },
  {
    id: "1291",
    title: "Operations Research",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Business & Management",
    series: "Management & Business Studies Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/eJdnCwAAQBAJ.jpg",
    buyLinks: [gp("eJdnCwAAQBAJ")],
  },
  {
    id: "1285",
    title: "Organizational Behavior",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Business & Management",
    series: "Management & Business Studies Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/f5RdDwAAQBAJ.jpg",
    buyLinks: [gp("f5RdDwAAQBAJ")],
  },
  {
    id: "1271",
    title: "Project Management",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Business & Management",
    series: "Management & Business Studies Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/OfiSBAAAQBAJ.jpg",
    buyLinks: [gp("OfiSBAAAQBAJ")],
  },
  {
    id: "1269",
    title: "Business Studies",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Business & Management",
    series: "Management & Business Studies Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/WIReDwAAQBAJ.jpg",
    buyLinks: [gp("WIReDwAAQBAJ")],
  },
  {
    id: "1265",
    title: "Database Management System",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Business & Management",
    series: "Management & Business Studies Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/0E2TBwAAQBAJ.jpg",
    buyLinks: [gp("0E2TBwAAQBAJ")],
  },
  {
    id: "1261",
    title: "Strategic Management",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Business & Management",
    series: "Management & Business Studies Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/e03lDAAAQBAJ.jpg",
    buyLinks: [gp("e03lDAAAQBAJ")],
  },
  {
    id: "1253",
    title: "Supply Chain Management",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Business & Management",
    series: "Management & Business Studies Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/zY_CBwAAQBAJ.jpg",
    buyLinks: [gp("zY_CBwAAQBAJ")],
  },
  {
    id: "1247",
    title: "Advertising and Sales Promotion",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Business & Management",
    series: "Management & Business Studies Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/oDdjBAAAQBAJ.jpg",
    buyLinks: [gp("oDdjBAAAQBAJ")],
  },
  {
    id: "1243",
    title: "Business Statistics and Data Processing",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Business & Management",
    series: "Management & Business Studies Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/uk8DCgAAQBAJ.jpg",
    buyLinks: [gp("uk8DCgAAQBAJ")],
  },
  {
    id: "1237",
    title: "Principles of Management",
    author: "Knowledge Flow",
    price: 9.99,
    category: "Business & Management",
    series: "Management & Business Studies Series",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/PUTIDAAAQBAJ.jpg",
    buyLinks: [gp("PUTIDAAAQBAJ")],
  },

  // ── Educational Books ──────────────────────────────────────────────────────
  {
    id: "1343",
    title: "NEET Combined Mock Test 2020",
    author: "Knowledge Flow",
    price: 7.99,
    category: "Educational Books",
    series: "Test Preparation & Review",
    coverImage: "https://knowledgeflowbooks.com/wp-content/uploads/2025/11/npTaDwAAQBAJ.jpg",
    buyLinks: [gp("npTaDwAAQBAJ")],
  },
];

export const BOOKS: Book[] = RAW.map(b => ({
  ...b,
  description: BOOK_DESCRIPTIONS[b.id],
}));

export const TESTIMONIALS = [
  {
    quote: "Knowledge Flow books have been an incredible resource for my engineering studies. Clear, concise, and comprehensive.",
    name: "Priya S.",
    role: "Mechanical Engineering Student"
  },
  {
    quote: "I passed my medical entrance exam thanks to the NEET mock test book. The format is exactly what you need for exam prep.",
    name: "Rahul M.",
    role: "Medical Student"
  },
  {
    quote: "The Python Programming book is perfect for beginners. I went from zero coding knowledge to building my first project.",
    name: "James T.",
    role: "Software Developer"
  }
];
